# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jorge Castillo
tagline:          'Android Dev'
description:      'Senior Android Dev'
url:              http://jorgecastillo.xyz
baseurl:          /

author:
  name:           'Jorge Castillo'
  url:            https://twitter.com/JorgeCastilloPr

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/JorgeCastilloPrz/jorgecastilloprz.github.io
