# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jorge Castillo
tagline:          'Android Dev'
description:      'Android Dev'
url:              http://jorgecastillo.xyz
baseurl:          /

author:
  name:           'Jorge Castillo'
  url:            https://twitter.com/JorgeCastilloPr

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/JorgeCastilloPrz/jorgecastilloprz.github.io

# Social Media Content
twitter_username: jorgecastillopr
github_username:  jorgecastilloprz
googleplus_username: +JorgeCastilloP%C3%A9rez
linkedin_username: jorgecastilloprz
